services:
  ainexus:
    image: ainexus
    build:
      context: .
      dockerfile: AiNexus/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

    ports:
      - "8080:8080"
      - "8081:8081"

    volumes:
      - ${APPDATA}/ASP.NET/Https:/https:ro